import Footer from '@/component/molecules/Footer'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'mmulyana | Frontend developer',
  description: 'Generated by create next app',
}

type Props = {
  children: React.ReactNode
}

export default function RootLayout({ children }: Props) {
  return (
    <html lang='en' className={inter.className}>
      <body className='container max-w-[800px]'>
        {children}
        <Footer />
      </body>
    </html>
  )
}
